packages:
  # all packages in direct subdirs of packages/
  - "core/packages/volto"
  - "core/packages/types"
  - "core/packages/registry"
  - "core/packages/components"
  - "core/packages/scripts"
  - "core/packages/volto-razzle"
  - "core/packages/volto-babel-preset-razzle"
  - "core/packages/volto-razzle-dev-utils"
  - "core/packages/tsconfig"
  - "core/packages/volto-slate"
  - "core/packages/coresandbox"
  - "packages/*"
