name: Code Analysis

on:
  push:

jobs:
  black:
    name: Black
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'black'

  flake8:
    name: flake8
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'flake8'

  isort:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'isort'
