name: Release new Docker image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: plone/frontend
  PLATFORMS: linux/amd64,linux/arm64
  IS_LATEST: false

jobs:

  meta:
    runs-on: ubuntu-latest
    outputs:
      BASE_IMAGE_NAME: ${{ steps.vars.outputs.BASE_IMAGE_NAME }}
      IS_LATEST: ${{ steps.vars.outputs.IS_LATEST }}
      PLATFORMS: ${{ steps.vars.outputs.PLATFORMS }}
      VOLTO_VERSION: ${{ steps.vars.outputs.VOLTO_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set BASE_IMAGE_NAME, IS_LATEST, PLATFORMS, VOLTO_VERSION
        id: vars
        run: |
          echo "BASE_IMAGE_NAME=$BASE_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "PLATFORMS=$PLATFORMS" >> $GITHUB_OUTPUT
          echo "IS_LATEST=$IS_LATEST" >> $GITHUB_OUTPUT
          echo "VOLTO_VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

  builder-image:
    needs:
      - meta
    uses: ./.github/workflows/image-release.yml
    with:
      volto-version: ${{ needs.meta.outputs.VOLTO_VERSION }}
      image-name: ${{ needs.meta.outputs.BASE_IMAGE_NAME }}-builder-next
      dockerfile: next/Dockerfile.builder
      platforms: ${{ needs.meta.outputs.PLATFORMS  }}
      is-latest: ${{ needs.meta.outputs.IS_LATEST == 'true'  }}
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}

  prod-conf-image:
    uses: ./.github/workflows/image-release.yml
    with:
      volto-version: ${{ needs.meta.outputs.VOLTO_VERSION }}
      image-name: ${{ needs.meta.outputs.BASE_IMAGE_NAME }}-prod-config-next
      dockerfile: next/Dockerfile.prod
      platforms: ${{ needs.meta.outputs.PLATFORMS  }}
      is-latest: ${{ needs.meta.outputs.IS_LATEST == 'true'  }}

    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - meta

  dev-image:
    uses: ./.github/workflows/image-release.yml
    with:
      volto-version: ${{ needs.meta.outputs.VOLTO_VERSION }}
      image-name: ${{ needs.meta.outputs.BASE_IMAGE_NAME }}-dev-next
      dockerfile: next/Dockerfile.dev
      platforms: ${{ needs.meta.outputs.PLATFORMS  }}
      is-latest: ${{ needs.meta.outputs.IS_LATEST == 'true'  }}
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - meta
      - builder-image

  plone-frontend:
    uses: ./.github/workflows/image-release.yml
    with:
      volto-version: ${{ needs.meta.outputs.VOLTO_VERSION }}
      image-name: plone/plone-frontend-next
      dockerfile: next/Dockerfile
      platforms: ${{ needs.meta.outputs.PLATFORMS  }}
      is-latest: ${{ needs.meta.outputs.IS_LATEST == 'true'  }}
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - meta
      - builder-image
      - prod-conf-image
