name: Runner Test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: [self-hosted, ARM64, Linux, unstable]
    environment: DOCKER_HUB

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            plone/plone-frontend
          # update label with proper version number
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 3000:3000 plone/plone-frontend:buildtest
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=buildtest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: Dockerfile.builder
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
